# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fed_proto.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64_proto.proto\x12\x0b\x66\x65\x64_package\"l\n\x0cgrad_request\x12\x1d\n\x15server_grad_para_data\x18\x01 \x03(\x0c\x12\x1d\n\x15server_grad_para_type\x18\x02 \x03(\t\x12\x1e\n\x16server_grad_para_shape\x18\x03 \x03(\t\"j\n\ngrad_reply\x12\x1d\n\x15\x63lient_grad_para_data\x18\x01 \x03(\x0c\x12\x1d\n\x15\x63lient_grad_para_type\x18\x02 \x03(\t\x12\x1e\n\x16\x63lient_grad_para_shape\x18\x03 \x03(\t\" \n\x10\x64\x61tasize_request\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x1e\n\x0e\x64\x61tasize_reply\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x1f\n\x0cstop_request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nstop_reply\x12\x0f\n\x07message\x18\x01 \x01(\t2S\n\x0bGradService\x12\x44\n\x0cgrad_descent\x12\x19.fed_package.grad_request\x1a\x17.fed_package.grad_reply\"\x00\x32_\n\x0f\x44\x61tasizeService\x12L\n\x0cget_datasize\x12\x1d.fed_package.datasize_request\x1a\x1b.fed_package.datasize_reply\"\x00\x32K\n\x0bStopService\x12<\n\x04stop\x12\x19.fed_package.stop_request\x1a\x17.fed_package.stop_reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fed_proto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GRAD_REQUEST']._serialized_start=32
  _globals['_GRAD_REQUEST']._serialized_end=140
  _globals['_GRAD_REPLY']._serialized_start=142
  _globals['_GRAD_REPLY']._serialized_end=248
  _globals['_DATASIZE_REQUEST']._serialized_start=250
  _globals['_DATASIZE_REQUEST']._serialized_end=282
  _globals['_DATASIZE_REPLY']._serialized_start=284
  _globals['_DATASIZE_REPLY']._serialized_end=314
  _globals['_STOP_REQUEST']._serialized_start=316
  _globals['_STOP_REQUEST']._serialized_end=347
  _globals['_STOP_REPLY']._serialized_start=349
  _globals['_STOP_REPLY']._serialized_end=378
  _globals['_GRADSERVICE']._serialized_start=380
  _globals['_GRADSERVICE']._serialized_end=463
  _globals['_DATASIZESERVICE']._serialized_start=465
  _globals['_DATASIZESERVICE']._serialized_end=560
  _globals['_STOPSERVICE']._serialized_start=562
  _globals['_STOPSERVICE']._serialized_end=637
# @@protoc_insertion_point(module_scope)
